name: quizapp
description: QuizApp Built with Flutter & Firebase.

publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.13.1
  firebase_core_dart: ^1.0.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.3
  font_awesome_flutter: ^10.4.0
  google_fonts: ^5.0.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  json_annotation: 4.8.1
  firebase_core_platform_interface: ^4.8.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0


flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/
    - assets/covers/
    - assets/congrats.gif