// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPushQG270WWb6LQNjTZoNbP5u_0-ygU',
    appId: '1:373359372224:android:56c4de88d5b084650b0a25',
    messagingSenderId: '373359372224',
    projectId: 'quizapp-4595d',
    storageBucket: 'quizapp-4595d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSgKGNVw26QFeBtYx5IdHIB_vKE-tltns',
    appId: '1:373359372224:ios:5abea097538937cc0b0a25',
    messagingSenderId: '373359372224',
    projectId: 'quizapp-4595d',
    storageBucket: 'quizapp-4595d.appspot.com',
    androidClientId: '373359372224-8hld1n0nnb3qm965q7eg30k25cea54ig.apps.googleusercontent.com',
    iosClientId: '373359372224-eqkpppsrtas5dgkucs7i8jcd9srinmd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );
}
